# Generated by Django 5.1.4 on 2024-12-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('sueldo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consecionaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('modelo', models.IntegerField()),
                ('patente', models.CharField(max_length=7)),
                ('valor', models.IntegerField()),
                ('kilometraje', models.IntegerField()),
            ],
        ),
    ]
